### PR TITLE
Md2.0 wms wmts

### PR DESCRIPTION
**Pull request by PaulaRodrigo-Geograma**
Dear @MarcoMinghini 

We have created a new branch md2.0-wms-wmts for solving the conflicts with master.

This pull request will add the ETS for metadata 2.0, ETS for WMS and ETS for WMTS.

Regards

### CODE REVIEW

**Comment by MarcoMinghini** [comment]
Dear @PaulaRodrigo-Geograma, thanks for this. However I still see that there are many automatic checks which failed.

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini ,
We are working on it. We are not getting much information in the logs. It seems it is related with a duplicated ID but we do not know which one.
Regards

**Comment by PaulaRodrigo-Geograma** [comment]
Dear @MarcoMinghini

We have solved the duplicated ID issue. There were teststeps with the same ID in the ETS for wmts.

Now you should not have problems to merge.

Regards

**Comment by danielnavarrogeo** [comment]
Dear @MarcoMinghini 

We have solved the duplicated ID issue. There were teststeps with the same ID in the ETS for wmts.

Now you should not have problems to merge.

Regards

**Pull request merged**
