### PR TITLE
Modifications in ETS for issues #180, #189 and #182

### PR DESCRIPTION
**Pull request by inakidiazdecerio**
Pull requests: 

- #191
- #190
- #192

### CODE REVIEW

**Comment by michellutz** [comment]
The idea was to have bugfix releases deployed first on a test server, before we merge them into the master branch and deploy them into production. Since we don't yet have a testing server, how could we proceed? Could you deploy the bugfix release on your testing server, so we can try out the behaviour?

**Comment by MarcoMinghini** [comment]
Dear @inakidiazdecerio, following the new issue on the community space https://github.com/inspire-eu-validation/community/issues/30, we noticed that the edit to the code for solving #180 is probably not the one that was agreed. 

The assertion should check that the codeListValue attribute is "publication" AND ALSO that there is actually a non-empty value of the element `<CI_DateTypeCode>`.

We noticed that because the validation of the metadata mentioned in https://github.com/inspire-eu-validation/community/issues/30 in the staging instance passes. Instaed, it should not pass because there is no value 'publication' (i.e. there is an empty value) for the element `<gmd:CI_DateTypeCode>`.

Can you make a new PR to solve this?

**Comment by inakidiazdecerio** [comment]
Thank you @MarcoMinghini for your comments. We will make a pull request including the non-empty check.

Best regards.

**Comment by MarcoMinghini** [comment]
The [pull request](https://github.com/inspire-eu-validation/ets-repository/pull/194) was made and accepted.

**Pull request merged**
