### PR TITLE
Relax test for MD 2.0 C18

### PR DESCRIPTION
**Pull request by josemasensio**
Relax test for MD 2.0 C.18 
Corresponding issue [194](https://github.com/inspire-eu-validation/community/issues/194)

### CODE REVIEW

**Comment by danielnavarrogeo** [comment]
The validator finishes at C18 with a strange behaviour when an Anchor element is used pointing to a different url. It does not finishes running all tests.

Please check what is happening.

**Comment by danielnavarrogeo** [comment]
There are still cases where it should fail but it doesn't.

For example:

image

**Comment by MarcoMinghini** [comment]
Please try to address the Travis error, since these should not happen anymore.

**Comment by danielnavarrogeo** [comment]
The Travis error has been fixed. Thank you @MarcoMinghini for pointing it out.

**Pull request merged**
