### PR TITLE
Helpdesk

### PR DESCRIPTION
**Pull request by inakidiazdecerio**
Modifications in ETS for the following issues:

https://github.com/inspire-eu-validation/ets-repository/issues/130
https://github.com/inspire-eu-validation/ets-repository/issues/119
https://github.com/inspire-eu-validation/ets-repository/issues/127
https://github.com/inspire-eu-validation/metadata/issues/130

### CODE REVIEW

**Comment by inakidiazdecerio** [comment]
Dear @AntoRot,

Thank you for your review. We assume that the test you are referring to is the one explained in the issue (#130) and not the (#120). The issue (#120) is not solved in this pull request. The change to solve the (#130) is performed in the metadata/iso/ets-md-iso-bsxets.xml file after the line number 159. Please, see changes in the following link: 

https://github.com/inspire-eu-validation/ets-repository/pull/162/files/481a5dffaa4d1c3e3372663b5ae633406d8491ff

Is that ok? Thanks in advance.

**Comment by inakidiazdecerio** [comment]
Sure @jonherrmann, the version number of the ETS has been incremented.

https://github.com/inspire-eu-validation/ets-repository/pull/162/commits/a1714f364e9a45bfa31f9059445fa49b9453bd38

**Comment by michellutz** [comment]
Please wait with merging this pull request until comments on pull request 137 have been resolved and changes have been merged.

**Comment by inakidiazdecerio** [comment]
@michellutz we resolved all conflicts. Please continue with the merge.

**Pull request merged**
